// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvXNPXOpig2-o9FSjH49OVj7IG1cq0lk',
    appId: '1:400077738063:web:0014c7992513f1dc2fda3a',
    messagingSenderId: '400077738063',
    projectId: 'watching-movie-tv-series',
    authDomain: 'watching-movie-tv-series.firebaseapp.com',
    storageBucket: 'watching-movie-tv-series.appspot.com',
    measurementId: 'G-K5H0QG8MSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUFQ5UT3RVDyDEBqChyIX5ncFcPVMM30',
    appId: '1:400077738063:android:87344f8b3769decf2fda3a',
    messagingSenderId: '400077738063',
    projectId: 'watching-movie-tv-series',
    storageBucket: 'watching-movie-tv-series.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD2AnjpWZ4FhkoB2ECykrDviUj3SnC3ZI',
    appId: '1:400077738063:ios:9b7933be4e07c3cc2fda3a',
    messagingSenderId: '400077738063',
    projectId: 'watching-movie-tv-series',
    storageBucket: 'watching-movie-tv-series.appspot.com',
    iosClientId: '400077738063-r8midpu83arkpsmqq0k9ec44gtrp8arp.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
